version: '3.4'

services:
  asp-net-authorization-sample-web:
    container_name: asp-net-authorization-sample-web
    image: asp-net-authorization-sample-web
    build:
      context: .
      dockerfile: src/AspNetAuthorizationSample.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5001:5001"
  asp-net-authorization-sample-oidc:
    container_name: asp-net-authorization-sample-oidc
    image: mockserver/mockserver:mockserver-5.15.0
    ports:
      - 5002:5002
    environment:
      - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/requests.json
    volumes:
      - type: bind
        source: ./oidc-server
        target: /config
